#!/bin/sh

{% from "influxdb/map.jinja" import influxdb with context %}

PASS='{{ influxdb.root_pass }}'
#if [ "$PASS" = 'root' ]; then
#	PASS=$(openssl rand -hex 10)
#fi

touch /root/.influxdbpwd
chmod 0600 /root/.influxdbpwd
echo "machine localhost login root password $PASS" > /root/.influxdbpwd
curl -si 'http://localhost:8086/cluster_admins/root?u=root&p=root' -d '{"password": "{{ influxdb.root_pass }}"}' | grep '200 OK'

